//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortfolioStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortfolioStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroItex.Resources.Views.Portfolio.PortfolioStrings", typeof(PortfolioStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Assortment.
        /// </summary>
        public static string Assortment {
            get {
                return ResourceManager.GetString("Assortment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpets.
        /// </summary>
        public static string Carpets {
            get {
                return ResourceManager.GetString("Carpets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights.
        /// </summary>
        public static string Lights {
            get {
                return ResourceManager.GetString("Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string PortfolioTitle {
            get {
                return ResourceManager.GetString("PortfolioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC.
        /// </summary>
        public static string PVC {
            get {
                return ResourceManager.GetString("PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugs.
        /// </summary>
        public static string Rugs {
            get {
                return ResourceManager.GetString("Rugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runners.
        /// </summary>
        public static string Runners {
            get {
                return ResourceManager.GetString("Runners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the galery of our various types of goods that you can find in our stores..
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
    }
}
