//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroItex.Resources.Views.Home.HomeStrings", typeof(HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting.
        /// </summary>
        public static string Cutting {
            get {
                return ResourceManager.GetString("Cutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do cutting of bought goods to dimensions specified by the customer..
        /// </summary>
        public static string CuttingText {
            get {
                return ResourceManager.GetString("CuttingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We deliver the goods through our own fast and reliable delivery system..
        /// </summary>
        public static string DeliveryText {
            get {
                return ResourceManager.GetString("DeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find more in our stores.
        /// </summary>
        public static string ImagesMoreInfo {
            get {
                return ResourceManager.GetString("ImagesMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our most selling goods.
        /// </summary>
        public static string ImagesTitle {
            get {
                return ResourceManager.GetString("ImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of floor coverings.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether it is a carpet or PVC we do a quick and clean installation..
        /// </summary>
        public static string InstallationText {
            get {
                return ResourceManager.GetString("InstallationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why People like us?.
        /// </summary>
        public static string LikeUs {
            get {
                return ResourceManager.GetString("LikeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employees are friendly and welcoming. They offer a wide range of high quality goods and their service is fast and reliable..
        /// </summary>
        public static string LikeUsText1 {
            get {
                return ResourceManager.GetString("LikeUsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their service is the best and their products are really good..
        /// </summary>
        public static string LikeUsTitle1 {
            get {
                return ResourceManager.GetString("LikeUsTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am satisfied with their products..
        /// </summary>
        public static string LikeUsTitle2 {
            get {
                return ResourceManager.GetString("LikeUsTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are our proud partners with which we cooperate.
        /// </summary>
        public static string PartnersText {
            get {
                return ResourceManager.GetString("PartnersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular products.
        /// </summary>
        public static string PopularProduct {
            get {
                return ResourceManager.GetString("PopularProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The categories of products that are the most popular among our customers.
        /// </summary>
        public static string PopularProductText {
            get {
                return ResourceManager.GetString("PopularProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We manufacture our own line of high quality curtain rods..
        /// </summary>
        public static string ProductionText {
            get {
                return ResourceManager.GetString("ProductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a question or need more information?.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a call on +387 37 771 356, we are available every day from 08:00h to 16:00h (GMT+1) except Sundays..
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ridging.
        /// </summary>
        public static string Ridging {
            get {
                return ResourceManager.GetString("Ridging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do customized ridging of bought goods..
        /// </summary>
        public static string RidgingText {
            get {
                return ResourceManager.GetString("RidgingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
