//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroItex.Resources.Views.Services.ServicesStrings", typeof(ServicesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting.
        /// </summary>
        public static string Cutting {
            get {
                return ResourceManager.GetString("Cutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We doo cutting of bought goods to dimnesions specified by the customer..
        /// </summary>
        public static string CuttingText1 {
            get {
                return ResourceManager.GetString("CuttingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We deliver the goods through our own fast and reliable delivery system..
        /// </summary>
        public static string DeliveryText {
            get {
                return ResourceManager.GetString("DeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We make and install carpet stair treads..
        /// </summary>
        public static string ImagesMoreInfo {
            get {
                return ResourceManager.GetString("ImagesMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do ridging of bought goods..
        /// </summary>
        public static string ImagesMoreInfo1 {
            get {
                return ResourceManager.GetString("ImagesMoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and reliable delivery..
        /// </summary>
        public static string ImagesMoreInfo2 {
            get {
                return ResourceManager.GetString("ImagesMoreInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of carpets..
        /// </summary>
        public static string ImagesMoreInfo3 {
            get {
                return ResourceManager.GetString("ImagesMoreInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of PVC floor coverings..
        /// </summary>
        public static string ImagesMoreInfo4 {
            get {
                return ResourceManager.GetString("ImagesMoreInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do cutting on desired dimensions..
        /// </summary>
        public static string ImagesMoreInfo5 {
            get {
                return ResourceManager.GetString("ImagesMoreInfo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of floor coverings.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheter it is a carpet or PVC we do a quick and clean installation..
        /// </summary>
        public static string InstallationText {
            get {
                return ResourceManager.GetString("InstallationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our services.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We manufactaure our own line of hiqh qualtiy curtain rods..
        /// </summary>
        public static string ProductionText {
            get {
                return ResourceManager.GetString("ProductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ridging.
        /// </summary>
        public static string Ridging {
            get {
                return ResourceManager.GetString("Ridging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do customized ridging of bought goods..
        /// </summary>
        public static string RidgingText {
            get {
                return ResourceManager.GetString("RidgingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
